
# Jekyll config
auto: false
server: false
lsi: false
exclude: /shared
permalink: pretty
source: public
posts_include:
  - .textile
  - .markdown
api: true
url: 'http://localhost:4567'
language: en-US
destination: _posts

keys:
  google_analytics: ""
  mixpanel: ""

metadata:
  title: "Postable.me"
  description: "Blog Anywhere via Email"
  tagline: "Blog Anywhere via Email"
  author: "Viatropos - Lance Pollard"
  copyright: "Viatropos | All Rights Reserved"
  country: "United States"
  classification: Software by Example
  domain: http://viatropos.com
  keywords: "javascript, jquery, open-source, github, social-bookmarking, oauth, openid, facebook, twiiter, myspace, google, sinatra, ruby-on-rails, html, css"

# ICONS
icons:
  social:
    twitter: /shared/themes/pure/html/images/twitter.png
    facebook: /shared/themes/pure/html/images/facebook.png
    myspace: /shared/themes/pure/html/images/myspace.png
    rss: /shared/themes/pure/html/images/rss.png
    stumbleupon: /shared/themes/pure/html/images/stumbleupon.png

  favicon: "/images/icons/viatropos-favicon.png"
  touch_icon: "/images/icons/viatropos-touch-icon.png"
  site_icon: "/images/icons/viatropos-site-icon.png"

# IMAGES
images:
  logo:
    normal: " "
    small: " "
    title: ""

# LINKS
links:
  twitter: http://www.twitter.com/viatropos
  facebook: http://www.facebook.com/viatropos
  github: http://www.github.com/viatropos
  stack_overflow: http://stackoverflow.com/users/169992/viatropos
  digg: ""
  myspace: ""
  linked_in: ""

# FEATURED
featured: ""